### ISSUE TITLE
[Suggestion] Possibility to add QR code scanning for login?

### ISSUE THREAD

**Issue by AMufInABox** [ZixeSea/SteamIdler#6]
It sounds simpler if we could scan a QR code with Steam Guard to login to our account(s) rather then inputting a code every time. 

If it helps, i've seen SteamDB use QR codes when using one of their own programs
https://github.com/SteamDatabase/SteamTokenDumper/blob/master/Program.cs#L441
https://github.com/SteamRE/SteamKit/blob/master/Samples/1b.QrCodeAuthentication/Program.cs

**Comment by ZixeSea** [comment]
I'm not sure how I would be able to add a QR code to this because I want to keep it small and lightweight. This is also the reason it shows all info through the console instead of a full UI.

That said since update https://github.com/ZixeSea/SteamIdler/commit/2f0a814942000e732efeedc821e91bb20dab9f82 I have added the login token refresh meaning you only have to login 1 time and after that it should say logged in even if you completely close the program.
